#!/bin/bash

_term() {
  steamcmd-7daystodie-shutdown
}

trap _term SIGTERM

./7DaysToDieServer.x86_64 \
  -logfile /dev/stdout \
  -configfile=$CONFIG_FILE \
  -quit \
  -batchmode \
  -nographics \
  -dedicated &

child=$!
wait "$child"
