#!/usr/bin/env bash

shutdown() {
  steamcmd-7daystodie-rcon <<EOS
    shutdown
    exit
EOS
}

while true; do
  echo "Sending shutdown command.."
  shutdown && break
  echo "Trying again in 2 seconds.."
  sleep 2
done
